### ISSUE TITLE
cursor visual bug in features 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/mobile#2391]
1. open a feature with a text field 
2. start typing in the text field 
3. your cursor will be bugged out in the top left corner 
4. you are able to write, but cannot copy or select parts of your text 

Android 11, Xiaomi Redmi Note 10, Input 2.0.0
![IMG_20221125_111007](https://user-images.githubusercontent.com/94351263/203962985-aada9ea2-6dcb-43d1-91c3-f9cb35f54dd8.jpg)

**Comment by tomasMizera** [comment]
This seems to be a Qt bug in the end, see https://bugreports.qt.io/browse/QTBUG-100436

**Comment by PeterPetrik** [comment]
Should be fixed in 6.4.x and Qt 6.5.x, can we retest on https://github.com/MerginMaps/input/tree/dev-2.3 @jozef-budac ?

**Comment by tomasMizera** [comment]
Unfortunately, this issue has only been introduced in Qt 6.4.x, but let's give 6.5 a chance

**Comment by jozef-budac** [comment]
Is it still present in out latest Qt 6.5.x builds

**Comment by rastermanden** [comment]
We see this too and also a very slow text widget with 2-3 seconds delays when typing. Is this lagging possibly related to this issue?

**Comment by Uffeshub** [comment]
The slow text widget, that @rastermanden mentioned has somehow been fixed, but the cursor visual bug is still present. Any news on this bug?

**Comment by tomasMizera** [comment]
@jozef-budac / @PatrikMizera can you guys retest this please with the latest `master` version?

**Comment by tomasMizera** [comment]
@Uffeshub, this bug is, unfortunately, caused by our core dependency, we are waiting for its resolution in their code.

**Comment by jozef-budac** [comment]
Here it how it looks like in our current production and also current master:
https://github.com/MerginMaps/input/assets/83582181/d6c995ee-2574-4fe0-aa7b-7b271b4382d5

**Comment by PeterPetrik** [comment]
maybe fixed in https://github.com/MerginMaps/mobile/pull/2912 ?

**Comment by jozef-budac** [comment]
It is the same in QT 6.6.0

**Comment by tomasMizera** [comment]
Should now be hopefully sorted
